name: Build Service

on:
  workflow_dispatch:
  pull_request:
    paths-ignore: ['*.md']
    branches: ['master', 'next']
  push:
    paths-ignore: ['*.md']
    branches: ['master', 'next']

jobs:
  BuildPackage:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set up Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      - name: Get embassyOS Hash
        run: echo "EMBASSYHASH=$(git ls-remote https://github.com/Start9Labs/embassy-os HEAD | awk '{ print $1}')" >> $GITHUB_ENV
      - name: Cache Packages
        uses: actions/cache@v3
        id: packageCache
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-hello-world-${{ env.EMBASSYHASH }}
      - name: Install Dependencies
        run: |
          sudo snap install yq deno
          sudo apt-get install -y build-essential openssl libssl-dev libc6-dev clang libclang-dev ca-certificates
      - name: Checkout services repository
        uses: actions/checkout@v3
      - name: Install Package Manager
        id: packageManager
        if: steps.packageCache.outputs.cache-hit != 'true'
        run: |
          cd ~/ && git clone https://github.com/Start9Labs/embassy-os.git;
          cd embassy-os;
          git submodule update --init --recursive
          cd backend;
          export RUSTFLAGS="";
          ./install-sdk.sh;
      - name: Build the service package
        run: |
          git submodule update --init --recursive
          embassy-sdk init
          make
          mv hello-world*s9pk ~/
      - name: Upload .s9pk
        uses: actions/upload-artifact@v3
        with:
          name: hello-world.s9pk
          path: ~/*.s9pk
